theme: jekyll-theme-minimal
title: Welcome to Sarah Rider's Home Page
descrption: This site is for practice creating a personal website. Feel free to browse this site to keep up with current projects, music recommendations, and recipe indexes. 
